def dockerHome
pipeline {
    agent {
          label 'docker'
    }
    stages {
        stage('Initialize'){
             steps{
                 script{
                    dockerHome = tool 'docker'
                    env.PATH = "${dockerHome}/bin:${env.PATH}"
                 }
                sh "cd ${dockerHome}/bin/ service docker start"
            }
        }
        stage('Build') {
            agent{
                docker {
                   image 'maven:3-alpine'
                   args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            agent{
                docker {
                   image 'maven:3-alpine'
                   args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            agent{
                docker {
                   image 'maven:3-alpine'
                   args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
